---
  # Title: Urbackup
  #
  # Author: bitfinity.nl
  # File: defaults/ubt-1804-amd64-enabled.yml
  #
  # Description:
  #   Backup server

  - name: "Add repository"
    apt_repository:
      repo: ppa:uroni/urbackup
      state: present

  - name: "Install packages"
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apache2
      - urbackup-server

  - name: "Enable Apache2 modules"
    apache2_module:
      state: present
      name: "{{ item }}"
    with_items:
      - proxy
      - proxy_http
      - proxy_ajp
      - rewrite
      - deflate
      - headers
      - proxy_balancer
      - proxy_connect
      - proxy_html
    notify:
      - restart_apache

  - name: "Transfer templates"
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: 'ubt-1804-server/urbackup.conf.j2', dest: '/etc/apache2/sites-available/urbackup.conf'}
      - { src: 'ubt-1804-server/urbackup-ssl.conf.j2', dest: '/etc/apache2/sites-available/urbackup-ssl.conf'}
    notify:
      - restart_apache

  - name: "Disable default sites and enable UrBackup site"
    command: "a2dissite {{ item }}"
    with_items:
      - 000-default.conf
      - default-ssl.conf
    notify:
      - restart_apache
  
  - name: "Disable default sites and enable UrBackup site"
    command: "a2ensite {{ item }}"
    with_items:
      - urbackup.conf
      - urbackup-ssl.conf
    notify:
      - restart_apache

  - name: "Create symlink from /usr/share/urbackup/www to /var/www/urbackup"
    file:
      src: /usr/share/urbackup/www
      dest: /var/www/html/urbackup
      owner: www-data
      group: www-data
      state: link
  
  - name: "ufw allow traffic on specific ports"
    ufw:
      rule: allow
      direction: "{{ item.dir }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
    with_items:
      - { dir: 'in', port: '80', proto: 'tcp' }
      - { dir: 'in', port: '443', proto: 'tcp' }
      - { dir: 'in', port: '55415', proto: 'tcp' }
      - { dir: 'out', port: '35623', proto: 'udp' }
#      - { port: '55413', proto: 'tcp' }
#      - { port: '55414', proto: 'tcp' }