---
  # Title: Urbackup
  #
  # Author: bitfinity.nl
  # File: tasks/win-install-client.yml
  #
  # Description:
  #   UrBackup is an easy to setup 
  #   Open Source client/server backup system.

  - name: "Create local Ansible repository"
    win_file:
      path: "{{ ubk_win_cli_pkg_repo_local }}"
      state: directory
  
  - name: "Download Package"
    win_get_url:
      url: "{{ ubk_win_cli_pkg_repo_remote }}"
      dest: "{{ ubk_win_cli_pkg_installer }}"
      force: no 
  
  - name: "Installing {{ ubk_win_cli_pkg_name }}"
    win_package:
      path: "{{ ubk_win_cli_pkg_installer }}"
      product_id: "{{ ubk_win_cli_pkg_product_id }}"
      arguments: "{{ ubk_win_cli_pkg_arguments }}"
      state: present

  - name: "Removing installation files"
    win_file:
      path: "{{ ubk_win_cli_pkg_repo_local }}"
      state: absent 

 - name: "Configure Windows Firewall for UrBackup"
   win_firewall_rule:
     name: Zabbix Passive (10050)
     localport: "{{ item.port }}"
     action: allow
     direction: "{{ item.dir }}"
     protocol: "{{ item.proto }}"
     state: present
   with_items:
     - { dir: 'in', port: '35621', proto: 'tcp' }
     - { dir: 'in', port: '35622', proto: 'udp' }
     - { dir: 'in', port: '35623', proto: 'tcp' }
